[package]
name = "web_server_01"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
hyper = { version = "0.14", features = ["full"] }
serde_json = "1.0.140"
serde = "1.0.219"
form_urlencoded = "1.2.1"
